grant select on T_SCOB_SUBMATERIA to USR_SIA_INTFZ;
grant select on T_SCOB_AREA_COBRANZA to USR_SIA_INTFZ;
grant select on T_SCOB_EST_EXP_COB_MOTIVO to USR_SIA_INTFZ;
grant select on T_SCOB_USUARIO to USR_SIA_INTFZ;
grant select on T_SCOB_ARCHIVO_CENTRAL to USR_SIA_INTFZ;
grant select on T_SCOB_TABLA_DET to USR_SIA_INTFZ;

grant select on T_SCOB_MULTA_DENUNCIANTE to USR_SIA_INTFZ;
grant select on T_SCOB_MULTA_SANCIONADO to USR_SIA_INTFZ;

grant select on T_SCOB_MULTA_ARCHIVO_CENTRAL to USR_SIA_INTFZ;

grant select on EMPLEADOMAST to USR_SIA_INTFZ;
grant select on T_SCOB_MULTA_ARCHIVO_CENTRAL to USR_SIA_INTFZ;

grant select on T_SCOB_ENTIDAD_FINANCIERA to USR_SIA_INTFZ;
