SELECT MU.ANIO || MU.CUM AS NRO_CUM,
             DECODE(PE.TIPO_PERSONA,
                    2,
                    PE.RAZON_SOCIAL,
                    1,
                    PE.APE_PATERNO || ' ' || PE.APE_MATERNO || ' ' ||
                    PE.APE_CASADA || ' ' || PE.PRI_NOMBRE ||
                    DECODE(PE.SEG_NOMBRE, NULL, '', ' ' || PE.SEG_NOMBRE)) AS SANCIONADO,
             MU.ANIO_FILE_AEC || MU.NRO_FILE_AEC AS NRO_FILE,
             TO_CHAR(MU.FEC_INGRESO_AEC, 'YYYY-MM-DD') AS FEC_INGRESO,
             ESM.TXT_DESCRIPCION AS ESTADO_MULTA,
             EE.DESCRIPCION AS ESTADO_EXP,
             MD.VALOR_UIT AS UIT,
             MU.SALDO_TOTAL_DEUDA AS SALDO,
             MU.ID_MULTA,
             MS.ID_MULTA_SANCIONADO
        FROM USR_SICOB.T_SCOB_MULTA MU
       INNER JOIN USR_SICOB.T_SCOB_MULTA_DETAL MD
          ON (MU.ID_MULTA = MD.ID_MULTA AND MD.FLG_ACTUAL = '1')
       INNER JOIN USR_SICOB.T_SCOB_TABLA_DET ESM
          ON (MU.ESTADO_MULTA = ESM.COD_INTERNO AND ESM.ID_TABLA = 5)
       INNER JOIN USR_SICOB.T_SCOB_MULTA_SANCIONADO MS
          ON (MD.ID_MULTA_DETAL = MS.ID_MULTA_DETAL)
       INNER JOIN USR_SICOB.T_SCOB_PERSONA PE
          ON (MS.ID_PERSONA = PE.ID_PERSONA)
        LEFT OUTER JOIN USR_SICOB.T_SCOB_EXPEDIENTE_MULTA EM
          ON (MU.ID_MULTA = EM.ID_MULTA AND
             (EM.ESTADO = '1' OR EM.ESTADO IS NULL))
        LEFT OUTER JOIN USR_SICOB.T_SCOB_EXPEDIENTE EX
          ON (EM.ID_EXPEDIENTE = EX.ID_EXPEDIENTE AND
             (EX.ESTADO = '1' OR EX.ESTADO IS NULL))
        LEFT OUTER JOIN USR_SICOB.T_SCOB_EST_EXP_COB EE
          ON (EX.ESTADO_EXPEDIENTE = EE.CODIGO)
       WHERE MU.ESTADO = '1'
         AND MD.ESTADO = '1'
         AND MS.COD_TIPO_PERSONA = '1'
         AND MS.FLG_PRINCIPAL = '1'
         AND MS.ESTADO = '1'
         AND PE.ID_PERSONA = 1108;
         
SELECT * FROM T_SCOB_MULTA_SANCIONADO
SELECT * FROM T_SCOB_PERSONA
SELECT * FROM T_SCOB_MULTA
SELECT * FROM T_SCOB_MULTA_DETAL
SELECT ID_MULTA, count(*) FROM T_SCOB_MULTA_DETAL WHERE ESTADO=1 AND FLG_ACTUAL=1 gROUP BY ID_MULTA HAVING  count(*) > 1
SELECT * FROM T_SCOB_MULTA_DETAL WHERE ID_MULTA = 485;

UPDATE USR_SICOB.T_SCOB_MULTA_SANCIONADO MS 
SET MS.ID_PERSONA =PIN_ID_PERSONA_REEMPLAZO
, MS.AUDUSUMODIFICACION = PIN_VC_USUARIO
, MS. AUDFECMODIFICACION = SYSDATE 
WHERE MS.ID_MULTA_DETAL IN (SELECT EM.ID_MULTA_DETAL FROM USR_SICOB.T_SCOB_MULTA_DETAL EM WHERE 
         EM.ID_MULTA = PIN_NU_ID_MULTA)
AND MS.ID_PERSONA= PIN_ID_PERSONA_A_REEMPLAZAR;


   SELECT MS.*
     FROM USR_SICOB.T_SCOB_MULTA_SANCIONADO MS
    WHERE MS.ID_MULTA_DETAL IN
          (SELECT EM.ID_MULTA_DETAL
             FROM USR_SICOB.T_SCOB_MULTA_DETAL EM
            WHERE EM.ID_MULTA = P_ID_MULTA)
      AND MS.ID_PERSONA = P_ID_SANCIONADO_ANTIGUO;
